config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :tasks

  get '/tasks/markAsDone/:id' => 'tasks#markAsDone'
  get '/tasks/markAsUndone/:id' => 'tasks#markAsUndone'

end

app/models/task.rb
class Task < ActiveRecord::Base
	def markTheTaskAsDone
		self.isDone = true
		self.save
	end

	def markTheTaskAsUndone
		self.isDone = false
		self.save
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  	redirect_to '/tasks'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def create
		@task = Task.new(task_params)
		@task.save
	  	redirect_to '/tasks'
	end
	
	def index
		@tasks = Task.all
	end

	def show
		@task = Task.find(params[:id])
	end

	def new
		
	end

	def markAsDone
		@task = Task.find(params[:id])
		@task.markTheTaskAsDone
		redirect_to '/tasks'
	end

	def markAsUndone
		@task = Task.find(params[:id])
		@task.markTheTaskAsUndone
		redirect_to '/tasks'	
	end

	private
  	def task_params
    	params.require(:task).permit(:title, :isDone)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
  		<title>Happiness Planning</title>
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>

	<body>

		<div id="main-container" class="container">
			<div class="row">
				<div class="col-xs-3">
					<h3>Happiness Planning</h3>
				</div>
				<div class="col-xs-9">
					<%= yield %>
				</div>
			</div>
		</div>

	</body>
</html>

app/views/tasks/index.html.erb
<h1>Hello, let's plan your day now!</h1>

<h2>Tell me your three tasks that you want to complete today :)</h2>
(It doesn't necessarily need to be the most important or crucial tasks from your job, but what would make you feel great about your day)

<%= form_for :task, url: tasks_path do |f| %>

    <div class="form-group">
      <%= f.label :title, "Task:" %><br>
      <%= f.text_field :title, class: "form-control", placeholder: "Insert your task name here" %>
    </div>
  	 
 
  <p>
    <%= f.submit class:'btn btn-primary'%>
  </p>
<% end %>
</form>

<h2>Tasks that should be done today</h2>
 
<table class="table table-condensed table-bordered">
  <tr class="info">
    <th width="03%">ID</th>
    <th width="45%">Task</th>
    <th width="41%">Status</th>
  </tr>

  <% @tasks.each do |task| %>
    <% if not task.isDone %>
      
      <tr class="btn-danger">
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= link_to "Mark as Done!", "/tasks/markAsDone/#{task.id}", class: "btn btn-success"%>
        </td>    
      </tr>    
    <% end %>


  <% end %>
</table>

<h2>Tasks that were done today</h2>
 
<table class="table table-condensed table-bordered">
  <tr class="info">
    <th width="03%">ID</th>
    <th width="45%">Task</th>
    <th width="41%">Status</th>
  </tr>

  <% @tasks.each do |task| %>
    <% if task.isDone %>
      <tr class="btn-success">
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= link_to "Mark as Undone!", "/tasks/markAsUndone/#{task.id}", class: "btn btn-danger"%>
        </td>    
      </tr>
    <% end %>


  <% end %>
</table>